### ISSUE TITLE
Incorrect paths after installing with pip

### ISSUE THREAD

**Issue by stucox** [OnroerendErfgoed/language-tags#12]
After installing into a fresh virtualenv with pip, `import language_tags` throws an IOError trying to load the JSON data — see below.

```sh
$ mkdir tmp && cd tmp
$ mkvirtualenv tmp
New python executable in tmp/bin/python
Installing setuptools, pip...done.
(tmp)$ pip install language-tags
Downloading/unpacking language-tags
  Downloading language_tags-0.4.0-py2.py3-none-any.whl (206kB): 206kB downloaded
Downloading/unpacking six (from language-tags)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: language-tags, six
Successfully installed language-tags six
Cleaning up...
(tmp)$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import language_tags
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/.virtualenvs/tmp/lib/python2.7/site-packages/language_tags/__init__.py", line 1, in <module>
    from language_tags.tags import tags
  File "/path/to/.virtualenvs/tmp/lib/python2.7/site-packages/language_tags/tags.py", line 8, in <module>
    from language_tags.Subtag import Subtag
  File "/path/to/.virtualenvs/tmp/lib/python2.7/site-packages/language_tags/Subtag.py", line 10, in <module>
    index = json.load(open(os.path.join(parent_dir, data_dir + "index.json"), encoding='utf-8'))
IOError: [Errno 2] No such file or directory: '/path/to/.virtualenvs/tmp/lib/python2.7/site-packages/language_tags/../node_modules/language-subtag-registry/data/json/index.json'
```

tags.py uses:

```python
data_dir = '../node_modules/language-subtag-registry/data/json/'
```

… which presumably isn’t included by setup.py (and nor is a package.json to install any node_modules from — although tbh I really shouldn’t expect to do anything with node when using a Python package!)

The `data` dir *is* copied into `language_tags` though, so maybe this path should point there?

```python
data_dir = 'data/json/'
```

**Comment by cahytinne** [comment]
Apologies, I will release a new version as soon as possible.

**Comment by stucox** [comment]
Great, thanks.

**Comment by cahytinne** [comment]
This issue is fixed in the new release https://github.com/OnroerendErfgoed/language-tags/releases/tag/0.4.1

Thanks for reporting this!
